### ISSUE TITLE
Need help

### ISSUE THREAD

**Issue by Googaa0082** [LunarrBlue/PySpy#2]
Hello brother
I tried multiple times to get your rat working but it doesn't. Everytime I run into an error. Can you help me out a little? Discord bander0909  Help appreciated

**Comment by lunar-404** [comment]
I'd be glad to help, I'm adding you right now. My username is lunar_404_

**Comment by lunar-404** [comment]
Its also probably a problem with the packages, I will be fixing those problems in the next release, but I'm reworking almost everything
